version: 2.1
jobs:
 build:
   machine:
     image: ubuntu-2204:current
   steps:
     - checkout
     - run:
         name: Retrieve latest stable version of FastNetMon Advanced to use as part of Docker image name
         # Add source command to execute code and make variables
         # available in current step.
         command: |
            echo "export LATEST_FASTNETMON_VERSION=`curl -s https://storage.googleapis.com/fastnetmon_advanced_packages_unstable/ubuntu/22.04/fastnetmon_latest_version.dat`" >> "$BASH_ENV"
            cat "$BASH_ENV"
            source "$BASH_ENV"
     - run: echo "Latest version of FastNetMon is $LATEST_FASTNETMON_VERSION"
     - run: docker build . -t fastnetmonltd/fastnetmon-advanced:$LATEST_FASTNETMON_VERSION -t fastnetmonltd/fastnetmon-advanced:latest --build-arg FASTNETMON_VERSION=$LATEST_FASTNETMON_VERSION
     - run: sudo docker images
     - run: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
     - run: docker push fastnetmonltd/fastnetmon-advanced:$LATEST_FASTNETMON_VERSION
     - run: docker push fastnetmonltd/fastnetmon-advanced:latest

# We have two different workflows to trigger same tasks on commit and nightly
# We run this one to build Docker images for new release or to upgrade system packages for current release
workflows:
  version: 2
  all_distros_nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "30 2 * * *"
          filters:
            branches:
              only:
                - master
  all_distros:
    jobs:
      - build
