version: 2.1
parameters:
  fastnetmon_version:
    type: string
    default: "2.0.336"
jobs:
 build:
   machine:
     image: ubuntu-2204:current
   steps:
     - checkout
     - run:
         name: Retrieve latest stable version of FastNetMon Advanced to use as part of Docker image name
         # Add source command to execute code and make variables
         # available in current step.
         command: |
            echo "export LATEST_FASTNETMON_VERSION=`curl -s https://storage.googleapis.com/fastnetmon_advanced_packages_unstable/ubuntu/22.04/fastnetmon_latest_version.dat`" >> "$BASH_ENV"
            cat "$BASH_ENV"
            source "$BASH_ENV"
     - run: docker build . -t fastnetmonltd/fastnetmon-advanced:<< pipeline.parameters.fastnetmon_version >> -t fastnetmonltd/fastnetmon-advanced:latest --build-arg FASTNETMON_VERSION=<< pipeline.parameters.fastnetmon_version >>
     - run: sudo docker images
     - run: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
     - run: docker push fastnetmonltd/fastnetmon-advanced:<< pipeline.parameters.fastnetmon_version >>
     - run: docker push fastnetmonltd/fastnetmon-advanced:latest

